version: '3'

services:
  profilers:
    container_name: profilers
    build:
      context: profilers-service
      dockerfile: Dockerfile
    image: profilers:latest
    command: /root/miniconda2/bin/flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./profilers-service:/var/www/
    ports:
      - "5000:5000"
    networks:
      - profilers-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - profilers-network
  api:
    container_name: api
    build:
      context: backend
      dockerfile: Dockerfile
    image: api:latest
    # command: python app.py
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - profilers
      - mongodb
    networks:
      - profilers-network

  web:
    container_name: web
    build:
      context: frontend
      dockerfile: Dockerfile
    image: web:latest
    command: dockerize -wait tcp://profilers:5000 -timeout 300s npm run dev
    depends_on:
      - profilers
      - api
      - mongodb
    networks:
      - profilers-network
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules
networks:
  profilers-network:
    driver: bridge